version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - michael-kamel
  ignore:
  - dependency-name: snyk
    versions:
    - 1.437.3
    - 1.440.1
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: eslint-plugin-standard
    versions:
    - 5.0.0
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: bl
    versions:
    - 4.0.3
